// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct CryptoFilesystem CryptoFilesystem;
void __swift_bridge__$CryptoFilesystem$_free(void* self);

void* __swift_bridge__$Vec_CryptoFilesystem$new(void);
void __swift_bridge__$Vec_CryptoFilesystem$drop(void* vec_ptr);
void __swift_bridge__$Vec_CryptoFilesystem$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_CryptoFilesystem$pop(void* vec_ptr);
void* __swift_bridge__$Vec_CryptoFilesystem$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_CryptoFilesystem$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_CryptoFilesystem$len(void* vec_ptr);
void* __swift_bridge__$Vec_CryptoFilesystem$as_ptr(void* vec_ptr);

typedef struct FsResultFs FsResultFs;
void __swift_bridge__$FsResultFs$_free(void* self);

void* __swift_bridge__$Vec_FsResultFs$new(void);
void __swift_bridge__$Vec_FsResultFs$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultFs$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultFs$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultFs$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultFs$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultFs$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultFs$as_ptr(void* vec_ptr);

typedef struct FsResultAttrs FsResultAttrs;
void __swift_bridge__$FsResultAttrs$_free(void* self);

void* __swift_bridge__$Vec_FsResultAttrs$new(void);
void __swift_bridge__$Vec_FsResultAttrs$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultAttrs$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultAttrs$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultAttrs$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultAttrs$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultAttrs$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultAttrs$as_ptr(void* vec_ptr);

typedef struct FsResultStats FsResultStats;
void __swift_bridge__$FsResultStats$_free(void* self);

void* __swift_bridge__$Vec_FsResultStats$new(void);
void __swift_bridge__$Vec_FsResultStats$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultStats$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultStats$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultStats$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultStats$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultStats$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultStats$as_ptr(void* vec_ptr);

typedef struct FsResultDirEntries FsResultDirEntries;
void __swift_bridge__$FsResultDirEntries$_free(void* self);

void* __swift_bridge__$Vec_FsResultDirEntries$new(void);
void __swift_bridge__$Vec_FsResultDirEntries$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultDirEntries$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultDirEntries$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultDirEntries$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultDirEntries$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultDirEntries$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultDirEntries$as_ptr(void* vec_ptr);

typedef struct FsResultHandle FsResultHandle;
void __swift_bridge__$FsResultHandle$_free(void* self);

void* __swift_bridge__$Vec_FsResultHandle$new(void);
void __swift_bridge__$Vec_FsResultHandle$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultHandle$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultHandle$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultHandle$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultHandle$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultHandle$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultHandle$as_ptr(void* vec_ptr);

typedef struct FsResultUnit FsResultUnit;
void __swift_bridge__$FsResultUnit$_free(void* self);

void* __swift_bridge__$Vec_FsResultUnit$new(void);
void __swift_bridge__$Vec_FsResultUnit$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultUnit$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultUnit$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultUnit$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultUnit$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultUnit$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultUnit$as_ptr(void* vec_ptr);

typedef struct FsResultBytes FsResultBytes;
void __swift_bridge__$FsResultBytes$_free(void* self);

void* __swift_bridge__$Vec_FsResultBytes$new(void);
void __swift_bridge__$Vec_FsResultBytes$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultBytes$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultBytes$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultBytes$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultBytes$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultBytes$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultBytes$as_ptr(void* vec_ptr);

typedef struct FsResultWritten FsResultWritten;
void __swift_bridge__$FsResultWritten$_free(void* self);

void* __swift_bridge__$Vec_FsResultWritten$new(void);
void __swift_bridge__$Vec_FsResultWritten$drop(void* vec_ptr);
void __swift_bridge__$Vec_FsResultWritten$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FsResultWritten$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultWritten$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FsResultWritten$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FsResultWritten$len(void* vec_ptr);
void* __swift_bridge__$Vec_FsResultWritten$as_ptr(void* vec_ptr);

typedef struct FileAttributes FileAttributes;
void __swift_bridge__$FileAttributes$_free(void* self);

void* __swift_bridge__$Vec_FileAttributes$new(void);
void __swift_bridge__$Vec_FileAttributes$drop(void* vec_ptr);
void __swift_bridge__$Vec_FileAttributes$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FileAttributes$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FileAttributes$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FileAttributes$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FileAttributes$len(void* vec_ptr);
void* __swift_bridge__$Vec_FileAttributes$as_ptr(void* vec_ptr);

typedef struct DirectoryEntry DirectoryEntry;
void __swift_bridge__$DirectoryEntry$_free(void* self);

void* __swift_bridge__$Vec_DirectoryEntry$new(void);
void __swift_bridge__$Vec_DirectoryEntry$drop(void* vec_ptr);
void __swift_bridge__$Vec_DirectoryEntry$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_DirectoryEntry$pop(void* vec_ptr);
void* __swift_bridge__$Vec_DirectoryEntry$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_DirectoryEntry$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_DirectoryEntry$len(void* vec_ptr);
void* __swift_bridge__$Vec_DirectoryEntry$as_ptr(void* vec_ptr);

typedef struct VolumeStatistics VolumeStatistics;
void __swift_bridge__$VolumeStatistics$_free(void* self);

void* __swift_bridge__$Vec_VolumeStatistics$new(void);
void __swift_bridge__$Vec_VolumeStatistics$drop(void* vec_ptr);
void __swift_bridge__$Vec_VolumeStatistics$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_VolumeStatistics$pop(void* vec_ptr);
void* __swift_bridge__$Vec_VolumeStatistics$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_VolumeStatistics$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_VolumeStatistics$len(void* vec_ptr);
void* __swift_bridge__$Vec_VolumeStatistics$as_ptr(void* vec_ptr);

void* __swift_bridge__$crypto_fs_new(void* vault_path, void* password);
uint64_t __swift_bridge__$CryptoFilesystem$get_root_item_id(void* self);
void __swift_bridge__$CryptoFilesystem$shutdown(void* self);
void* __swift_bridge__$CryptoFilesystem$get_volume_stats(void* self);
void* __swift_bridge__$CryptoFilesystem$lookup(void* self, uint64_t parent_id, void* name);
void* __swift_bridge__$CryptoFilesystem$get_attributes(void* self, uint64_t item_id);
void* __swift_bridge__$CryptoFilesystem$enumerate_directory(void* self, uint64_t item_id, uint64_t cookie);
uint64_t __swift_bridge__$CryptoFilesystem$get_enumeration_cookie(void* self, uint64_t item_id, uint64_t cookie);
void* __swift_bridge__$CryptoFilesystem$open_file(void* self, uint64_t item_id, bool for_write);
void* __swift_bridge__$CryptoFilesystem$close_file(void* self, uint64_t handle);
void* __swift_bridge__$CryptoFilesystem$read_file(void* self, uint64_t handle, int64_t offset, int64_t length);
void* __swift_bridge__$CryptoFilesystem$write_file(void* self, uint64_t handle, int64_t offset, void* data);
void* __swift_bridge__$CryptoFilesystem$create_file(void* self, uint64_t parent_id, void* name);
void* __swift_bridge__$CryptoFilesystem$create_directory(void* self, uint64_t parent_id, void* name);
void* __swift_bridge__$CryptoFilesystem$create_symlink(void* self, uint64_t parent_id, void* name, void* target);
void* __swift_bridge__$CryptoFilesystem$remove(void* self, uint64_t parent_id, void* name, uint64_t item_id);
void* __swift_bridge__$CryptoFilesystem$rename(void* self, uint64_t src_parent_id, void* src_name, uint64_t dst_parent_id, void* dst_name, uint64_t item_id);
void* __swift_bridge__$CryptoFilesystem$read_symlink(void* self, uint64_t item_id);
void* __swift_bridge__$CryptoFilesystem$truncate(void* self, uint64_t item_id, uint64_t size);
void __swift_bridge__$CryptoFilesystem$reclaim(void* self, uint64_t item_id);
bool __swift_bridge__$FsResultFs$result_fs_is_ok(void* self);
int32_t __swift_bridge__$FsResultFs$result_fs_error(void* self);
void* __swift_bridge__$FsResultFs$result_fs_unwrap(void* self);
bool __swift_bridge__$FsResultAttrs$result_attrs_is_ok(void* self);
int32_t __swift_bridge__$FsResultAttrs$result_attrs_error(void* self);
void* __swift_bridge__$FsResultAttrs$result_attrs_unwrap(void* self);
bool __swift_bridge__$FsResultStats$result_stats_is_ok(void* self);
int32_t __swift_bridge__$FsResultStats$result_stats_error(void* self);
void* __swift_bridge__$FsResultStats$result_stats_unwrap(void* self);
bool __swift_bridge__$FsResultDirEntries$result_dir_is_ok(void* self);
int32_t __swift_bridge__$FsResultDirEntries$result_dir_error(void* self);
void* __swift_bridge__$FsResultDirEntries$result_dir_unwrap(void* self);
bool __swift_bridge__$FsResultHandle$result_handle_is_ok(void* self);
int32_t __swift_bridge__$FsResultHandle$result_handle_error(void* self);
uint64_t __swift_bridge__$FsResultHandle$result_handle_unwrap(void* self);
bool __swift_bridge__$FsResultUnit$result_unit_is_ok(void* self);
int32_t __swift_bridge__$FsResultUnit$result_unit_error(void* self);
bool __swift_bridge__$FsResultBytes$result_bytes_is_ok(void* self);
int32_t __swift_bridge__$FsResultBytes$result_bytes_error(void* self);
void* __swift_bridge__$FsResultBytes$result_bytes_unwrap(void* self);
bool __swift_bridge__$FsResultWritten$result_written_is_ok(void* self);
int32_t __swift_bridge__$FsResultWritten$result_written_error(void* self);
int64_t __swift_bridge__$FsResultWritten$result_written_unwrap(void* self);
uint64_t __swift_bridge__$FileAttributes$attr_item_id(void* self);
bool __swift_bridge__$FileAttributes$attr_is_directory(void* self);
bool __swift_bridge__$FileAttributes$attr_is_file(void* self);
bool __swift_bridge__$FileAttributes$attr_is_symlink(void* self);
uint64_t __swift_bridge__$FileAttributes$attr_size(void* self);
uint32_t __swift_bridge__$FileAttributes$attr_mode(void* self);
uint32_t __swift_bridge__$FileAttributes$attr_uid(void* self);
uint32_t __swift_bridge__$FileAttributes$attr_gid(void* self);
void* __swift_bridge__$DirectoryEntry$entry_name(void* self);
uint64_t __swift_bridge__$DirectoryEntry$entry_item_id(void* self);
bool __swift_bridge__$DirectoryEntry$entry_is_directory(void* self);
bool __swift_bridge__$DirectoryEntry$entry_is_file(void* self);
bool __swift_bridge__$DirectoryEntry$entry_is_symlink(void* self);
uint64_t __swift_bridge__$DirectoryEntry$entry_size(void* self);
uint64_t __swift_bridge__$VolumeStatistics$stats_total_bytes(void* self);
uint64_t __swift_bridge__$VolumeStatistics$stats_available_bytes(void* self);
uint64_t __swift_bridge__$VolumeStatistics$stats_used_bytes(void* self);
uint64_t __swift_bridge__$VolumeStatistics$stats_total_inodes(void* self);
uint64_t __swift_bridge__$VolumeStatistics$stats_available_inodes(void* self);
uint32_t __swift_bridge__$VolumeStatistics$stats_block_size(void* self);


